### ISSUE TITLE
Error on ESP32

### ISSUE THREAD

**Issue by Mahdinvs** [targetblank/micropython_ahtx0#4]
I get this error on ESP32:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
ImportError: no module named 'ahtx0'

and SCL is connected to GPIO 14, and SDA to GPIO 12

**Comment by thegreenlion42** [comment]
same on esp8266 (wemos d1 mini)

**Comment by rdiazlugo** [comment]
I had the same issue.
To solve it, I had to manually add the `ahtx0.py` file inside the `/lib` folder.

**Comment by PierreLaunay** [comment]
Hello

In order to use it, you have to download the file ahtx0.py first, and then in your IDE (MUEditor e.g.) you must import the file on your device (in Mu you select Files icon on the menu and you drag and drop the file from the right panel to the left one).

Once it is transferred, you can use the example shown in the Readme file. 
As to ESP32, change the 7th line:
i2c = I2C(scl=Pin(5), sda=Pin(4))
by :
i2c = I2C(scl=Pin(22), sda=Pin(21))

Good luck!

**Comment by targetblank** [comment]
Hi all, please try installing version 0.1.2, which should fix the import issue.
